### ISSUE TITLE
Compile on arm

### ISSUE THREAD

**Issue by RCasatta** [yacoin/yacoin#29]
i am trying to compile the source on arm achitecture without -msse2 option but i have an error

g++ -c -O2 -pthread -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter  -DBOOST_SPIRIT_THREADSAFE -I/home/odroid/yacoin/src -I/home/odroid/yacoin/src/obj -DUSE_UPNP=0 -DUSE_IPV6=1 -DSCRYPT_KECCAK512 -DSCRYPT_CHACHA -DSCRYPT_CHOOSE_COMPILETIME -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -MMD -MF obj/scrypt_mine.d -o obj/scrypt_mine.o scrypt_mine.cpp
scrypt_mine.cpp:32:23: fatal error: xmmintrin.h: No such file or directory
 #include <xmmintrin.h>

**Comment by feldenthorne** [comment]
I just fixed this issue in a Diamond fork, but I only kluged in support for armv7 (rather than all arm processors) because the whole process was pretty confusing. [Here's the commit, though](https://github.com/feldenthorne/Diamond/commit/01046753bf3e566d000854a41a2417493bd8db7c#diff-95108e0b0a2682866f3a99ead07809d2), and it should basically be a drop-in solution since your code is pretty similar.
